/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module counter_alu(clk, rst_n, cnt_en, op, a, b, cnt, alu_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire [7:0] _011_;
  wire [7:0] _012_;
  wire [7:0] _013_;
  wire [7:0] _014_;
  wire [7:0] _015_;
  wire _016_;
  wire [2:0] _017_;
  wire [7:0] _018_;
  wire [7:0] _019_;
  wire [7:0] _020_;
  wire [7:0] _021_;
  wire [7:0] _022_;
  wire [7:0] _023_;
  wire [7:0] _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  reg _034_;
  reg _035_ = 1'h0;
  reg _036_;
  reg _037_ = 1'h0;
  reg _038_;
  reg _039_ = 1'h0;
  reg _040_;
  reg _041_;
  reg _042_;
  reg _043_ = 1'h0;
  wire _044_;
  wire _045_;
  wire [7:0] _046_;
  wire [7:0] _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire [7:0] _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire [7:0] _061_;
  wire [7:0] _062_;
  wire [7:0] _063_;
  wire [7:0] _064_;
  wire [7:0] _065_;
  wire [7:0] _066_;
  wire [7:0] _067_;
  input [7:0] a;
  wire [7:0] a;
  reg [7:0] a_d = 8'h00;
  output [7:0] alu_out;
  wire [7:0] alu_out;
  reg [7:0] alu_out_d = 8'h00;
  input [7:0] b;
  wire [7:0] b;
  reg [7:0] b_d = 8'h00;
  input clk;
  wire clk;
  output [7:0] cnt;
  reg [7:0] cnt = 8'h00;
  reg [7:0] cnt_d = 8'h00;
  input cnt_en;
  wire cnt_en;
  reg cnt_en_d = 1'h0;
  input [2:0] op;
  wire [2:0] op;
  reg [2:0] op_d = 3'h0;
  input rst_n;
  wire rst_n;
  reg rst_n_d = 1'h0;
  assign _019_ = cnt_d + 1'h1;
  assign _020_ = a + b;
  assign _021_ = cnt + 1'h1;
  assign _022_ = a_d + b_d;
  assign _023_ = a & b;
  assign _024_ = a_d & b_d;
  always @* if (_035_) assert(_034_);
  always @* if (_037_) assert(_036_);
  always @* if (_039_) assert(_038_);
  always @* if (rst_n_d) assert(_040_);
  always @* if (rst_n_d) assert(_041_);
  always @* if (_043_) assert(_042_);
  assign _025_ = cnt == _019_;
  assign _026_ = cnt == cnt_d;
  assign _027_ = ! cnt;
  assign _028_ = alu_out_d == _018_;
  assign _029_ = cnt_d == 8'hff;
  assign _030_ = ! op;
  assign _031_ = op == 1'h1;
  assign _032_ = op == 2'h2;
  assign _033_ = op == 2'h3;
  assign _044_ = cnt_en_d && _029_;
  assign _045_ = op < 3'h5;
  assign _046_ = a | b;
  assign _047_ = a_d | b_d;
  always @(posedge clk)
    rst_n_d <= _007_;
  always @(posedge clk)
    cnt_en_d <= _016_;
  always @(posedge clk)
    cnt_d <= _015_;
  always @(posedge clk)
    op_d <= _017_;
  always @(posedge clk)
    a_d <= _011_;
  always @(posedge clk)
    b_d <= _013_;
  always @(posedge clk)
    alu_out_d <= _012_;
  always @(posedge clk)
    _034_ <= _000_;
  always @(posedge clk)
    _035_ <= _001_;
  always @(posedge clk)
    _036_ <= _002_;
  always @(posedge clk)
    _037_ <= _003_;
  always @(posedge clk)
    _038_ <= _004_;
  always @(posedge clk)
    _039_ <= _005_;
  always @(posedge clk)
    _040_ <= _006_;
  always @(posedge clk)
    _041_ <= _008_;
  always @(posedge clk)
    _042_ <= _009_;
  always @(posedge clk)
    _043_ <= _010_;
  always @(posedge clk, negedge rst_n)
    if (!rst_n) cnt <= 8'h00;
    else cnt <= _014_;
  assign _017_ = rst_n ? op : 3'h0;
  assign _015_ = rst_n ? cnt : 8'h00;
  assign _016_ = rst_n ? cnt_en : 1'h0;
  assign _007_ = rst_n ? 1'h1 : 1'h0;
  assign _048_ = cnt_en_d ? 1'h1 : 1'h0;
  assign _001_ = rst_n ? _048_ : 1'h0;
  assign _049_ = cnt_en_d ? _025_ : 1'hx;
  assign _000_ = rst_n ? _049_ : 1'hx;
  assign _050_ = cnt_en_d ? 1'h0 : 1'h1;
  assign _003_ = rst_n ? _050_ : 1'h0;
  assign _051_ = cnt_en_d ? 1'hx : _026_;
  assign _002_ = rst_n ? _051_ : 1'hx;
  assign _052_ = rst_n_d ? 1'h0 : 1'h1;
  assign _005_ = rst_n ? _052_ : 1'h0;
  assign _053_ = rst_n_d ? 1'hx : _027_;
  assign _004_ = rst_n ? _053_ : 1'hx;
  assign _006_ = rst_n ? _028_ : 1'hx;
  assign _008_ = rst_n ? _045_ : 1'hx;
  assign _054_ = _044_ ? 1'h1 : 1'h0;
  assign _010_ = rst_n ? _054_ : 1'h0;
  assign _055_ = _044_ ? _027_ : 1'hx;
  assign _009_ = rst_n ? _055_ : 1'hx;
  assign _014_ = cnt_en ? _021_ : cnt;
  function [7:0] _134_;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _134_ = b[7:0];
      4'b??1?:
        _134_ = b[15:8];
      4'b?1??:
        _134_ = b[23:16];
      4'b1???:
        _134_ = b[31:24];
      default:
        _134_ = a;
    endcase
  endfunction
  assign _056_ = _134_(_067_, { _022_, _062_, _024_, _047_ }, { _060_, _059_, _058_, _057_ });
  assign _057_ = op_d == 2'h3;
  assign _058_ = op_d == 2'h2;
  assign _059_ = op_d == 1'h1;
  assign _060_ = ! op_d;
  assign _018_ = rst_n ? _056_ : 8'hxx;
  assign _012_ = rst_n ? alu_out : 8'h00;
  assign _013_ = rst_n ? b : 8'h00;
  assign _011_ = rst_n ? a : 8'h00;
  assign _061_ = a - b;
  assign _062_ = a_d - b_d;
  assign alu_out = _030_ ? _020_ : _063_;
  assign _063_ = _031_ ? _061_ : _064_;
  assign _064_ = _032_ ? _023_ : _065_;
  assign _065_ = _033_ ? _046_ : _066_;
  assign _066_ = a ^ b;
  assign _067_ = a_d ^ b_d;
endmodule
